[features]
seeds = true #set to true to enable automatic PDA derivation in TS builder API
[programs.devnet]
voting_dapp = "AoiWJZFUbBksdydYiX6N7tUDWojYZupRyWtZGVd7rF4E"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/zunairajaved/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
